name: Deploy to Hugging Face Space
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://sarkar-abhranshu:${HF_TOKEN}@huggingface.co/spaces/sarkar-abhranshu/papermind
          git push hf HEAD:main --force
